### PR TITLE
Fix jsonata evaluation in filename field

### LINKED ISSUE #37: JSONata not evaluated in read/write file nodes in the context of Node-RED 3.1.0
### Current Behavior

A flow with `write file` and `read file` nodes using a `$join(['a','b','c'])` JSONata expression for the filename, will use that expression string verbatim as filename, rather than evaluating it to 'abc'.

This happens on docker image flowforge/node-red:1.13.2-3.1.0, while on flowforge/node-red:1.13.2 the expression is evaluated.

It would seem related to:
- https://github.com/node-red/node-red/pull/4246
- https://github.com/node-red/node-red-nodes/issues/1011

### Expected Behavior

The nodes should evaluate the expression and use the filename 'abc'.

### Steps To Reproduce

Import and trigger this flow on a flowforge/node-red:1.13.2-3.1.0 instance.
```
[{"id":"9533c737d8b1bf9c","type":"tab","label":"JSONata filename bug","disabled":false,"info":"","env":[]},{"id":"314d9f0b4e0ac1ed","type":"debug","z":"9533c737d8b1bf9c","name":"debug write","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":550,"y":340,"wires":[]},{"id":"45965d8ef17a431e","type":"file","z":"9533c737d8b1bf9c","name":"","filename":"$join(['a','b','c'])","filenameType":"jsonata","appendNewline":true,"createDir":true,"overwriteFile":"true","encoding":"none","x":380,"y":340,"wires":[["314d9f0b4e0ac1ed","4e1b46a0d777dcf3"]]},{"id":"3214f4b4233a57c2","type":"inject","z":"9533c737d8b1bf9c","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":220,"y":340,"wires":[["45965d8ef17a431e"]]},{"id":"4e1b46a0d777dcf3","type":"file in","z":"9533c737d8b1bf9c","name":"","filename":"$join(['a','b','c'])","filenameType":"jsonata","format":"utf8","chunk":false,"sendError":false,"encoding":"none","allProps":false,"x":540,"y":400,"wires":[["c5da2eb62b8327f4"]]},{"id":"c5da2eb62b8327f4","type":"debug","z":"9533c737d8b1bf9c","name":"debug read","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":710,"y":400,"wires":[]}]
``` 

### Environment

- FlowFuse version: 1.13.2
- FF Node-RED: flowforge/node-red:1.13.2-3.1.0@sha256:a82ebd2d5d38edb356f1ef12ccc36b568ce37ac1a6401dd2529a549d86950fa2
- Platform/OS: docker, linux/amd64

### PR DESCRIPTION
**Pull request by knolleary**
Fixes #37

## Description

This is a cross-port of https://github.com/node-red/node-red/pull/4246 to fix the handling of jsonata in the filename field.

### CODE REVIEW

File: file.js [hunk 1]
```diff
@@ -262,136 +265,134 @@ module.exports = function (RED) {
                     node.filenameType = 'str'
                 }
             }
-            let propertyError = false
             RED.util.evaluateNodeProperty(node.filename, node.filenameType, node, msg, (err, value) => {
                 if (err) {
                     node.error(err, msg)
-                    propertyError = true
-                    // return done()
+                    return done()
```
Comment (Steve-Mcl) [inline file.js:271]:
```suggestion
                    return nodeDone()
```

**Review by Steve-Mcl — CHANGES_REQUESTED** [review]
Line 66 should be const (this PR moves the place it was previously updated out of scope)

File: file.js (hunk 1 above)
Comment (knolleary) [reply file.js]: Fixed via https://github.com/FlowFuse/nr-file-nodes/pull/38/commits/0d016ad7362411094b4bc406f44916c7ddd21b15

**Review by Steve-Mcl — APPROVED** [review]
